name: deploy-prod
on:
  push:
    branches:
      - master
jobs:
  deploy-hosting:
    name: Deploy hosting to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Deploy website hosting
        run: cd hosting && yarn deploy
  deploy-functions:
    name: Deploy functions to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Deploy Firebase functions
        run: cd functions && yarn deploy
